# Dockerfile.dev
FROM ruby:3.4.8

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libsqlite3-dev \
  nodejs \
  npm \
  git \
  libvips \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN chmod +x ./bin/dev-entrypoint

EXPOSE 3000

CMD ["./bin/dev-entrypoint"]